language: rust
cache:
  directories:
  - /home/travis/.cargo
sudo: false
addons:
  apt:
    packages:
    - libssl-dev

rust:
- 1.20.0    # Oldest supported
#- stable   # Done by explicit job
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly
  include:
  - env: TEST
    rust: stable
    script: |
      set -e
      cargo test --verbose --features "use_serde ${TRAVIS_RUST_VERSION//./_}"
      cargo test --manifest-path tests/feature_check/Cargo.toml --verbose --features "${TRAVIS_RUST_VERSION//./_}"
      cargo test --verbose --no-default-features --features "autoconvert f32 f64 si use_serde ${TRAVIS_RUST_VERSION//./_}"
      cargo test --verbose --no-run --no-default-features --features "autoconvert usize u8 u16 u32 u64 isize i8 i16 i32 i64 bigint biguint rational rational32 rational64 bigrational f32 f64 std use_serde ${TRAVIS_RUST_VERSION//./_}"
  - env: RUSTFMT
    rust: stable
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --check
  - env: RUSTFLAGS="-D warnings"
    rust: stable
    script:
    - RUSTFLAGS="-D warnings" cargo check --tests
  - env: CLIPPY
    rust: stable
    install:
    - rustup component add clippy-preview
    script:
    - cargo clippy -- -D clippy
  - env: TARPAULIN
    rust: stable
    sudo: required
    script:
    - docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin sh -c "cargo build && cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID"

install:
- rustc -Vv
- cargo -V

script: |
  set -e
  cargo test --verbose --features "use_serde ${TRAVIS_RUST_VERSION//./_}"
  cargo test --manifest-path tests/feature_check/Cargo.toml --verbose --features "${TRAVIS_RUST_VERSION//./_}"

before_cache:
- rm -rf /home/travis/.cargo/registry

notifications:
  email:
    on_success: never
